// Code generated by MockGen. DO NOT EDIT.
// Source: wedding-invitation-backend/internal/repository/mongodb (interfaces: AnalyticsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	bson "go.mongodb.org/mongo-driver/bson/primitive"
	mongo "go.mongodb.org/mongo-driver/mongo"
	gomock "github.com/golang/mock/gomock"

	models "wedding-invitation-backend/internal/domain/models"
)

// MockAnalyticsRepository is a mock of AnalyticsRepository interface.
type MockAnalyticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsRepositoryMockRecorder
}

// MockAnalyticsRepositoryMockRecorder is the mock recorder for MockAnalyticsRepository.
type MockAnalyticsRepositoryMockRecorder struct {
	mock *MockAnalyticsRepository
}

// NewMockAnalyticsRepository creates a new mock instance.
func NewMockAnalyticsRepository(ctrl *gomock.Controller) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{ctrl: ctrl}
	mock.recorder = &MockAnalyticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepositoryMockRecorder {
	return m.recorder
}

// CleanupOldAnalytics mocks base method.
func (m *MockAnalyticsRepository) CleanupOldAnalytics(ctx context.Context, olderThan time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupOldAnalytics", ctx, olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupOldAnalytics indicates an expected call of CleanupOldAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) CleanupOldAnalytics(ctx, olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupOldAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).CleanupOldAnalytics), ctx, olderThan)
}

// GetAnalyticsSummary mocks base method.
func (m *MockAnalyticsRepository) GetAnalyticsSummary(ctx context.Context, weddingID bson.ObjectID, period string) (*models.AnalyticsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalyticsSummary", ctx, weddingID, period)
	ret0, _ := ret[0].(*models.AnalyticsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalyticsSummary indicates an expected call of GetAnalyticsSummary.
func (mr *MockAnalyticsRepositoryMockRecorder) GetAnalyticsSummary(ctx, weddingID, period interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalyticsSummary", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetAnalyticsSummary), ctx, weddingID, period)
}

// GetConversions mocks base method.
func (m *MockAnalyticsRepository) GetConversions(ctx context.Context, weddingID bson.ObjectID, filter *models.AnalyticsFilter) ([]*models.ConversionEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversions", ctx, weddingID, filter)
	ret0, _ := ret[0].([]*models.ConversionEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetConversions indicates an expected call of GetConversions.
func (mr *MockAnalyticsRepositoryMockRecorder) GetConversions(ctx, weddingID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversions", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetConversions), ctx, weddingID, filter)
}

// GetDailyMetrics mocks base method.
func (m *MockAnalyticsRepository) GetDailyMetrics(ctx context.Context, weddingID bson.ObjectID, startDate, endDate time.Time) ([]models.DailyMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyMetrics", ctx, weddingID, startDate, endDate)
	ret0, _ := ret[0].([]models.DailyMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyMetrics indicates an expected call of GetDailyMetrics.
func (mr *MockAnalyticsRepositoryMockRecorder) GetDailyMetrics(ctx, weddingID, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyMetrics", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetDailyMetrics), ctx, weddingID, startDate, endDate)
}

// GetPageViews mocks base method.
func (m *MockAnalyticsRepository) GetPageViews(ctx context.Context, weddingID bson.ObjectID, filter *models.AnalyticsFilter) ([]*models.PageView, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageViews", ctx, weddingID, filter)
	ret0, _ := ret[0].([]*models.PageView)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPageViews indicates an expected call of GetPageViews.
func (mr *MockAnalyticsRepositoryMockRecorder) GetPageViews(ctx, weddingID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageViews", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetPageViews), ctx, weddingID, filter)
}

// GetPopularPages mocks base method.
func (m *MockAnalyticsRepository) GetPopularPages(ctx context.Context, weddingID bson.ObjectID, limit int) ([]models.PageStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularPages", ctx, weddingID, limit)
	ret0, _ := ret[0].([]models.PageStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularPages indicates an expected call of GetPopularPages.
func (mr *MockAnalyticsRepositoryMockRecorder) GetPopularPages(ctx, weddingID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularPages", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetPopularPages), ctx, weddingID, limit)
}

// GetRSVPAnalytics mocks base method.
func (m *MockAnalyticsRepository) GetRSVPAnalytics(ctx context.Context, weddingID bson.ObjectID, filter *models.AnalyticsFilter) ([]*models.RSVPAnalytics, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRSVPAnalytics", ctx, weddingID, filter)
	ret0, _ := ret[0].([]*models.RSVPAnalytics)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRSVPAnalytics indicates an expected call of GetRSVPAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) GetRSVPAnalytics(ctx, weddingID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRSVPAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetRSVPAnalytics), ctx, weddingID, filter)
}

// GetSystemAnalytics mocks base method.
func (m *MockAnalyticsRepository) GetSystemAnalytics(ctx context.Context) (*models.SystemAnalytics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemAnalytics", ctx)
	ret0, _ := ret[0].(*models.SystemAnalytics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemAnalytics indicates an expected call of GetSystemAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) GetSystemAnalytics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetSystemAnalytics), ctx)
}

// GetTrafficSources mocks base method.
func (m *MockAnalyticsRepository) GetTrafficSources(ctx context.Context, weddingID bson.ObjectID, limit int) ([]models.TrafficSourceStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrafficSources", ctx, weddingID, limit)
	ret0, _ := ret[0].([]models.TrafficSourceStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrafficSources indicates an expected call of GetTrafficSources.
func (mr *MockAnalyticsRepositoryMockRecorder) GetTrafficSources(ctx, weddingID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrafficSources", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetTrafficSources), ctx, weddingID, limit)
}

// GetWeddingAnalytics mocks base method.
func (m *MockAnalyticsRepository) GetWeddingAnalytics(ctx context.Context, weddingID bson.ObjectID) (*models.WeddingAnalytics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeddingAnalytics", ctx, weddingID)
	ret0, _ := ret[0].(*models.WeddingAnalytics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeddingAnalytics indicates an expected call of GetWeddingAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) GetWeddingAnalytics(ctx, weddingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeddingAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetWeddingAnalytics), ctx, weddingID)
}

// TrackConversion mocks base method.
func (m *MockAnalyticsRepository) TrackConversion(ctx context.Context, event *models.ConversionEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackConversion", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackConversion indicates an expected call of TrackConversion.
func (mr *MockAnalyticsRepositoryMockRecorder) TrackConversion(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConversion", reflect.TypeOf((*MockAnalyticsRepository)(nil).TrackConversion), ctx, event)
}

// TrackPageView mocks base method.
func (m *MockAnalyticsRepository) TrackPageView(ctx context.Context, pageView *models.PageView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackPageView", ctx, pageView)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackPageView indicates an expected call of TrackPageView.
func (mr *MockAnalyticsRepositoryMockRecorder) TrackPageView(ctx, pageView interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackPageView", reflect.TypeOf((*MockAnalyticsRepository)(nil).TrackPageView), ctx, pageView)
}

// TrackRSVPEvent mocks base method.
func (m *MockAnalyticsRepository) TrackRSVPEvent(ctx context.Context, event *models.RSVPAnalytics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackRSVPEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackRSVPEvent indicates an expected call of TrackRSVPEvent.
func (mr *MockAnalyticsRepositoryMockRecorder) TrackRSVPEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackRSVPEvent", reflect.TypeOf((*MockAnalyticsRepository)(nil).TrackRSVPEvent), ctx, event)
}

// UpdateSystemAnalytics mocks base method.
func (m *MockAnalyticsRepository) UpdateSystemAnalytics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSystemAnalytics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSystemAnalytics indicates an expected call of UpdateSystemAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) UpdateSystemAnalytics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSystemAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).UpdateSystemAnalytics), ctx)
}

// UpdateWeddingAnalytics mocks base method.
func (m *MockAnalyticsRepository) UpdateWeddingAnalytics(ctx context.Context, weddingID bson.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWeddingAnalytics", ctx, weddingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWeddingAnalytics indicates an expected call of UpdateWeddingAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) UpdateWeddingAnalytics(ctx, weddingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWeddingAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).UpdateWeddingAnalytics), ctx, weddingID)
}

// EnsureIndexes mocks base method.
func (m *MockAnalyticsRepository) EnsureIndexes(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureIndexes", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureIndexes indicates an expected call of EnsureIndexes.
func (mr *MockAnalyticsRepositoryMockRecorder) EnsureIndexes(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureIndexes", reflect.TypeOf((*MockAnalyticsRepository)(nil).EnsureIndexes), ctx)
}

// MockWeddingRepository is a mock of WeddingRepository interface.
type MockWeddingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWeddingRepositoryMockRecorder
}

// MockWeddingRepositoryMockRecorder is the mock recorder for MockWeddingRepository.
type MockWeddingRepositoryMockRecorder struct {
	mock *MockWeddingRepository
}

// NewMockWeddingRepository creates a new mock instance.
func NewMockWeddingRepository(ctrl *gomock.Controller) *MockWeddingRepository {
	mock := &MockWeddingRepository{ctrl: ctrl}
	mock.recorder = &MockWeddingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeddingRepository) EXPECT() *MockWeddingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWeddingRepository) Create(ctx context.Context, wedding *models.Wedding) (*mongo.InsertOneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, wedding)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWeddingRepositoryMockRecorder) Create(ctx, wedding interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWeddingRepository)(nil).Create), ctx, wedding)
}

// Delete mocks base method.
func (m *MockWeddingRepository) Delete(ctx context.Context, id bson.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWeddingRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWeddingRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockWeddingRepository) GetByID(ctx context.Context, id bson.ObjectID) (*models.Wedding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Wedding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWeddingRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWeddingRepository)(nil).GetByID), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockWeddingRepository) GetBySlug(ctx context.Context, slug string) (*models.Wedding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(*models.Wedding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockWeddingRepositoryMockRecorder) GetBySlug(ctx, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockWeddingRepository)(nil).GetBySlug), ctx, slug)
}

// List mocks base method.
func (m *MockWeddingRepository) List(ctx context.Context, filter interface{}, options interface{}) ([]*models.Wedding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, options)
	ret0, _ := ret[0].([]*models.Wedding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWeddingRepositoryMockRecorder) List(ctx, filter, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWeddingRepository)(nil).List), ctx, filter, options)
}

// Update mocks base method.
func (m *MockWeddingRepository) Update(ctx context.Context, id bson.ObjectID, wedding *models.Wedding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, wedding)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWeddingRepositoryMockRecorder) Update(ctx, id, wedding interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWeddingRepository)(nil).Update), ctx, id, wedding)
}

// GetPublicWeddings mocks base method.
func (m *MockWeddingRepository) GetPublicWeddings(ctx context.Context, limit, offset int) ([]*models.Wedding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicWeddings", ctx, limit, offset)
	ret0, _ := ret[0].([]*models.Wedding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicWeddings indicates an expected call of GetPublicWeddings.
func (mr *MockWeddingRepositoryMockRecorder) GetPublicWeddings(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicWeddings", reflect.TypeOf((*MockWeddingRepository)(nil).GetPublicWeddings), ctx, limit, offset)
}

// GetUserWeddings mocks base method.
func (m *MockWeddingRepository) GetUserWeddings(ctx context.Context, userID bson.ObjectID, limit, offset int) ([]*models.Wedding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWeddings", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*models.Wedding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWeddings indicates an expected call of GetUserWeddings.
func (mr *MockWeddingRepositoryMockRecorder) GetUserWeddings(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWeddings", reflect.TypeOf((*MockWeddingRepository)(nil).GetUserWeddings), ctx, userID, limit, offset)
}