// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"
	models "wedding-invitation-backend/internal/domain/models"
	repository "wedding-invitation-backend/internal/domain/repository"

	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddWeddingID mocks base method.
func (m *MockUserRepository) AddWeddingID(ctx context.Context, userID, weddingID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWeddingID", ctx, userID, weddingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWeddingID indicates an expected call of AddWeddingID.
func (mr *MockUserRepositoryMockRecorder) AddWeddingID(ctx, userID, weddingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWeddingID", reflect.TypeOf((*MockUserRepository)(nil).AddWeddingID), ctx, userID, weddingID)
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id primitive.ObjectID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// GetByResetToken mocks base method.
func (m *MockUserRepository) GetByResetToken(ctx context.Context, token string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByResetToken", ctx, token)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByResetToken indicates an expected call of GetByResetToken.
func (mr *MockUserRepositoryMockRecorder) GetByResetToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByResetToken", reflect.TypeOf((*MockUserRepository)(nil).GetByResetToken), ctx, token)
}

// GetByVerificationToken mocks base method.
func (m *MockUserRepository) GetByVerificationToken(ctx context.Context, token string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByVerificationToken", ctx, token)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByVerificationToken indicates an expected call of GetByVerificationToken.
func (mr *MockUserRepositoryMockRecorder) GetByVerificationToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByVerificationToken", reflect.TypeOf((*MockUserRepository)(nil).GetByVerificationToken), ctx, token)
}

// List mocks base method.
func (m *MockUserRepository) List(ctx context.Context, page, pageSize int, filters repository.UserFilters) ([]*models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, pageSize, filters)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(ctx, page, pageSize, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), ctx, page, pageSize, filters)
}

// RemoveWeddingID mocks base method.
func (m *MockUserRepository) RemoveWeddingID(ctx context.Context, userID, weddingID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWeddingID", ctx, userID, weddingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWeddingID indicates an expected call of RemoveWeddingID.
func (mr *MockUserRepositoryMockRecorder) RemoveWeddingID(ctx, userID, weddingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWeddingID", reflect.TypeOf((*MockUserRepository)(nil).RemoveWeddingID), ctx, userID, weddingID)
}

// SetEmailVerified mocks base method.
func (m *MockUserRepository) SetEmailVerified(ctx context.Context, userID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmailVerified", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEmailVerified indicates an expected call of SetEmailVerified.
func (mr *MockUserRepositoryMockRecorder) SetEmailVerified(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmailVerified", reflect.TypeOf((*MockUserRepository)(nil).SetEmailVerified), ctx, userID)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, user)
}

// UpdateLastLogin mocks base method.
func (m *MockUserRepository) UpdateLastLogin(ctx context.Context, userID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockUserRepositoryMockRecorder) UpdateLastLogin(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockUserRepository)(nil).UpdateLastLogin), ctx, userID)
}

// MockWeddingRepository is a mock of WeddingRepository interface.
type MockWeddingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWeddingRepositoryMockRecorder
}

// MockWeddingRepositoryMockRecorder is the mock recorder for MockWeddingRepository.
type MockWeddingRepositoryMockRecorder struct {
	mock *MockWeddingRepository
}

// NewMockWeddingRepository creates a new mock instance.
func NewMockWeddingRepository(ctrl *gomock.Controller) *MockWeddingRepository {
	mock := &MockWeddingRepository{ctrl: ctrl}
	mock.recorder = &MockWeddingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeddingRepository) EXPECT() *MockWeddingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWeddingRepository) Create(ctx context.Context, wedding *models.Wedding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, wedding)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWeddingRepositoryMockRecorder) Create(ctx, wedding interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWeddingRepository)(nil).Create), ctx, wedding)
}

// Delete mocks base method.
func (m *MockWeddingRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWeddingRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWeddingRepository)(nil).Delete), ctx, id)
}

// ExistsBySlug mocks base method.
func (m *MockWeddingRepository) ExistsBySlug(ctx context.Context, slug string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsBySlug", ctx, slug)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsBySlug indicates an expected call of ExistsBySlug.
func (mr *MockWeddingRepositoryMockRecorder) ExistsBySlug(ctx, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsBySlug", reflect.TypeOf((*MockWeddingRepository)(nil).ExistsBySlug), ctx, slug)
}

// GetByID mocks base method.
func (m *MockWeddingRepository) GetByID(ctx context.Context, id primitive.ObjectID) (*models.Wedding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Wedding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWeddingRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWeddingRepository)(nil).GetByID), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockWeddingRepository) GetBySlug(ctx context.Context, slug string) (*models.Wedding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(*models.Wedding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockWeddingRepositoryMockRecorder) GetBySlug(ctx, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockWeddingRepository)(nil).GetBySlug), ctx, slug)
}

// GetByUserID mocks base method.
func (m *MockWeddingRepository) GetByUserID(ctx context.Context, userID primitive.ObjectID, page, pageSize int, filters repository.WeddingFilters) ([]*models.Wedding, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, page, pageSize, filters)
	ret0, _ := ret[0].([]*models.Wedding)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockWeddingRepositoryMockRecorder) GetByUserID(ctx, userID, page, pageSize, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockWeddingRepository)(nil).GetByUserID), ctx, userID, page, pageSize, filters)
}

// IncrementViewCount mocks base method.
func (m *MockWeddingRepository) IncrementViewCount(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementViewCount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementViewCount indicates an expected call of IncrementViewCount.
func (mr *MockWeddingRepositoryMockRecorder) IncrementViewCount(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementViewCount", reflect.TypeOf((*MockWeddingRepository)(nil).IncrementViewCount), ctx, id)
}

// ListPublic mocks base method.
func (m *MockWeddingRepository) ListPublic(ctx context.Context, page, pageSize int, filters repository.PublicWeddingFilters) ([]*models.Wedding, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublic", ctx, page, pageSize, filters)
	ret0, _ := ret[0].([]*models.Wedding)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPublic indicates an expected call of ListPublic.
func (mr *MockWeddingRepositoryMockRecorder) ListPublic(ctx, page, pageSize, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublic", reflect.TypeOf((*MockWeddingRepository)(nil).ListPublic), ctx, page, pageSize, filters)
}

// Update mocks base method.
func (m *MockWeddingRepository) Update(ctx context.Context, wedding *models.Wedding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, wedding)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWeddingRepositoryMockRecorder) Update(ctx, wedding interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWeddingRepository)(nil).Update), ctx, wedding)
}

// UpdateRSVPCount mocks base method.
func (m *MockWeddingRepository) UpdateRSVPCount(ctx context.Context, weddingID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRSVPCount", ctx, weddingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRSVPCount indicates an expected call of UpdateRSVPCount.
func (mr *MockWeddingRepositoryMockRecorder) UpdateRSVPCount(ctx, weddingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRSVPCount", reflect.TypeOf((*MockWeddingRepository)(nil).UpdateRSVPCount), ctx, weddingID)
}

// MockRSVPRepository is a mock of RSVPRepository interface.
type MockRSVPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRSVPRepositoryMockRecorder
}

// MockRSVPRepositoryMockRecorder is the mock recorder for MockRSVPRepository.
type MockRSVPRepositoryMockRecorder struct {
	mock *MockRSVPRepository
}

// NewMockRSVPRepository creates a new mock instance.
func NewMockRSVPRepository(ctrl *gomock.Controller) *MockRSVPRepository {
	mock := &MockRSVPRepository{ctrl: ctrl}
	mock.recorder = &MockRSVPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRSVPRepository) EXPECT() *MockRSVPRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRSVPRepository) Create(ctx context.Context, rsvp *models.RSVP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rsvp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRSVPRepositoryMockRecorder) Create(ctx, rsvp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRSVPRepository)(nil).Create), ctx, rsvp)
}

// Delete mocks base method.
func (m *MockRSVPRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRSVPRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRSVPRepository)(nil).Delete), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockRSVPRepository) GetByEmail(ctx context.Context, weddingID primitive.ObjectID, email string) (*models.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, weddingID, email)
	ret0, _ := ret[0].(*models.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockRSVPRepositoryMockRecorder) GetByEmail(ctx, weddingID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockRSVPRepository)(nil).GetByEmail), ctx, weddingID, email)
}

// GetByID mocks base method.
func (m *MockRSVPRepository) GetByID(ctx context.Context, id primitive.ObjectID) (*models.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRSVPRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRSVPRepository)(nil).GetByID), ctx, id)
}

// GetStatistics mocks base method.
func (m *MockRSVPRepository) GetStatistics(ctx context.Context, weddingID primitive.ObjectID) (*models.RSVPStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", ctx, weddingID)
	ret0, _ := ret[0].(*models.RSVPStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockRSVPRepositoryMockRecorder) GetStatistics(ctx, weddingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockRSVPRepository)(nil).GetStatistics), ctx, weddingID)
}

// GetSubmissionTrend mocks base method.
func (m *MockRSVPRepository) GetSubmissionTrend(ctx context.Context, weddingID primitive.ObjectID, days int) ([]models.DailyCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmissionTrend", ctx, weddingID, days)
	ret0, _ := ret[0].([]models.DailyCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmissionTrend indicates an expected call of GetSubmissionTrend.
func (mr *MockRSVPRepositoryMockRecorder) GetSubmissionTrend(ctx, weddingID, days interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmissionTrend", reflect.TypeOf((*MockRSVPRepository)(nil).GetSubmissionTrend), ctx, weddingID, days)
}

// ListByWedding mocks base method.
func (m *MockRSVPRepository) ListByWedding(ctx context.Context, weddingID primitive.ObjectID, page, pageSize int, filters repository.RSVPFilters) ([]*models.RSVP, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByWedding", ctx, weddingID, page, pageSize, filters)
	ret0, _ := ret[0].([]*models.RSVP)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByWedding indicates an expected call of ListByWedding.
func (mr *MockRSVPRepositoryMockRecorder) ListByWedding(ctx, weddingID, page, pageSize, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByWedding", reflect.TypeOf((*MockRSVPRepository)(nil).ListByWedding), ctx, weddingID, page, pageSize, filters)
}

// MarkConfirmationSent mocks base method.
func (m *MockRSVPRepository) MarkConfirmationSent(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkConfirmationSent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkConfirmationSent indicates an expected call of MarkConfirmationSent.
func (mr *MockRSVPRepositoryMockRecorder) MarkConfirmationSent(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkConfirmationSent", reflect.TypeOf((*MockRSVPRepository)(nil).MarkConfirmationSent), ctx, id)
}

// Update mocks base method.
func (m *MockRSVPRepository) Update(ctx context.Context, rsvp *models.RSVP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rsvp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRSVPRepositoryMockRecorder) Update(ctx, rsvp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRSVPRepository)(nil).Update), ctx, rsvp)
}

// MockGuestRepository is a mock of GuestRepository interface.
type MockGuestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGuestRepositoryMockRecorder
}

// MockGuestRepositoryMockRecorder is the mock recorder for MockGuestRepository.
type MockGuestRepositoryMockRecorder struct {
	mock *MockGuestRepository
}

// NewMockGuestRepository creates a new mock instance.
func NewMockGuestRepository(ctrl *gomock.Controller) *MockGuestRepository {
	mock := &MockGuestRepository{ctrl: ctrl}
	mock.recorder = &MockGuestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuestRepository) EXPECT() *MockGuestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGuestRepository) Create(ctx context.Context, guest *models.Guest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, guest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGuestRepositoryMockRecorder) Create(ctx, guest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGuestRepository)(nil).Create), ctx, guest)
}

// CreateMany mocks base method.
func (m *MockGuestRepository) CreateMany(ctx context.Context, guests []*models.Guest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMany", ctx, guests)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMany indicates an expected call of CreateMany.
func (mr *MockGuestRepositoryMockRecorder) CreateMany(ctx, guests interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMany", reflect.TypeOf((*MockGuestRepository)(nil).CreateMany), ctx, guests)
}

// Delete mocks base method.
func (m *MockGuestRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGuestRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGuestRepository)(nil).Delete), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockGuestRepository) GetByEmail(ctx context.Context, weddingID primitive.ObjectID, email string) (*models.Guest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, weddingID, email)
	ret0, _ := ret[0].(*models.Guest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockGuestRepositoryMockRecorder) GetByEmail(ctx, weddingID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockGuestRepository)(nil).GetByEmail), ctx, weddingID, email)
}

// GetByID mocks base method.
func (m *MockGuestRepository) GetByID(ctx context.Context, id primitive.ObjectID) (*models.Guest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Guest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGuestRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGuestRepository)(nil).GetByID), ctx, id)
}

// GetByImportBatch mocks base method.
func (m *MockGuestRepository) GetByImportBatch(ctx context.Context, weddingID primitive.ObjectID, batchID string) ([]*models.Guest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByImportBatch", ctx, weddingID, batchID)
	ret0, _ := ret[0].([]*models.Guest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByImportBatch indicates an expected call of GetByImportBatch.
func (mr *MockGuestRepositoryMockRecorder) GetByImportBatch(ctx, weddingID, batchID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByImportBatch", reflect.TypeOf((*MockGuestRepository)(nil).GetByImportBatch), ctx, weddingID, batchID)
}

// ImportBatch mocks base method.
func (m *MockGuestRepository) ImportBatch(ctx context.Context, guests []*models.Guest, batchID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportBatch", ctx, guests, batchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportBatch indicates an expected call of ImportBatch.
func (mr *MockGuestRepositoryMockRecorder) ImportBatch(ctx, guests, batchID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportBatch", reflect.TypeOf((*MockGuestRepository)(nil).ImportBatch), ctx, guests, batchID)
}

// ListByWedding mocks base method.
func (m *MockGuestRepository) ListByWedding(ctx context.Context, weddingID primitive.ObjectID, page, pageSize int, filters repository.GuestFilters) ([]*models.Guest, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByWedding", ctx, weddingID, page, pageSize, filters)
	ret0, _ := ret[0].([]*models.Guest)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByWedding indicates an expected call of ListByWedding.
func (mr *MockGuestRepositoryMockRecorder) ListByWedding(ctx, weddingID, page, pageSize, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByWedding", reflect.TypeOf((*MockGuestRepository)(nil).ListByWedding), ctx, weddingID, page, pageSize, filters)
}

// Update mocks base method.
func (m *MockGuestRepository) Update(ctx context.Context, guest *models.Guest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, guest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGuestRepositoryMockRecorder) Update(ctx, guest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGuestRepository)(nil).Update), ctx, guest)
}

// MockMediaRepository is a mock of MediaRepository interface.
type MockMediaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMediaRepositoryMockRecorder
}

// MockMediaRepositoryMockRecorder is the mock recorder for MockMediaRepository.
type MockMediaRepositoryMockRecorder struct {
	mock *MockMediaRepository
}

// NewMockMediaRepository creates a new mock instance.
func NewMockMediaRepository(ctrl *gomock.Controller) *MockMediaRepository {
	mock := &MockMediaRepository{ctrl: ctrl}
	mock.recorder = &MockMediaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaRepository) EXPECT() *MockMediaRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMediaRepository) Create(ctx context.Context, media *models.Media) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, media)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMediaRepositoryMockRecorder) Create(ctx, media interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMediaRepository)(nil).Create), ctx, media)
}

// Delete mocks base method.
func (m *MockMediaRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMediaRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMediaRepository)(nil).Delete), ctx, id)
}

// GetByCreatedBy mocks base method.
func (m *MockMediaRepository) GetByCreatedBy(ctx context.Context, userID primitive.ObjectID, opts repository.ListOptions) ([]*models.Media, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCreatedBy", ctx, userID, opts)
	ret0, _ := ret[0].([]*models.Media)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByCreatedBy indicates an expected call of GetByCreatedBy.
func (mr *MockMediaRepositoryMockRecorder) GetByCreatedBy(ctx, userID, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCreatedBy", reflect.TypeOf((*MockMediaRepository)(nil).GetByCreatedBy), ctx, userID, opts)
}

// GetByID mocks base method.
func (m *MockMediaRepository) GetByID(ctx context.Context, id primitive.ObjectID) (*models.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMediaRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMediaRepository)(nil).GetByID), ctx, id)
}

// GetByStorageKey mocks base method.
func (m *MockMediaRepository) GetByStorageKey(ctx context.Context, key string) (*models.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStorageKey", ctx, key)
	ret0, _ := ret[0].(*models.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStorageKey indicates an expected call of GetByStorageKey.
func (mr *MockMediaRepositoryMockRecorder) GetByStorageKey(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStorageKey", reflect.TypeOf((*MockMediaRepository)(nil).GetByStorageKey), ctx, key)
}

// GetOrphaned mocks base method.
func (m *MockMediaRepository) GetOrphaned(ctx context.Context, before time.Time) ([]*models.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrphaned", ctx, before)
	ret0, _ := ret[0].([]*models.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrphaned indicates an expected call of GetOrphaned.
func (mr *MockMediaRepositoryMockRecorder) GetOrphaned(ctx, before interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrphaned", reflect.TypeOf((*MockMediaRepository)(nil).GetOrphaned), ctx, before)
}

// List mocks base method.
func (m *MockMediaRepository) List(ctx context.Context, filter repository.MediaFilter, opts repository.ListOptions) ([]*models.Media, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, opts)
	ret0, _ := ret[0].([]*models.Media)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockMediaRepositoryMockRecorder) List(ctx, filter, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMediaRepository)(nil).List), ctx, filter, opts)
}

// SoftDelete mocks base method.
func (m *MockMediaRepository) SoftDelete(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockMediaRepositoryMockRecorder) SoftDelete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockMediaRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockMediaRepository) Update(ctx context.Context, media *models.Media) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, media)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMediaRepositoryMockRecorder) Update(ctx, media interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMediaRepository)(nil).Update), ctx, media)
}

// MockAnalyticsRepository is a mock of AnalyticsRepository interface.
type MockAnalyticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsRepositoryMockRecorder
}

// MockAnalyticsRepositoryMockRecorder is the mock recorder for MockAnalyticsRepository.
type MockAnalyticsRepositoryMockRecorder struct {
	mock *MockAnalyticsRepository
}

// NewMockAnalyticsRepository creates a new mock instance.
func NewMockAnalyticsRepository(ctrl *gomock.Controller) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{ctrl: ctrl}
	mock.recorder = &MockAnalyticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepositoryMockRecorder {
	return m.recorder
}

// CleanupOldAnalytics mocks base method.
func (m *MockAnalyticsRepository) CleanupOldAnalytics(ctx context.Context, olderThan time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupOldAnalytics", ctx, olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupOldAnalytics indicates an expected call of CleanupOldAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) CleanupOldAnalytics(ctx, olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupOldAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).CleanupOldAnalytics), ctx, olderThan)
}

// GetAnalyticsSummary mocks base method.
func (m *MockAnalyticsRepository) GetAnalyticsSummary(ctx context.Context, weddingID primitive.ObjectID, period string) (*models.AnalyticsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalyticsSummary", ctx, weddingID, period)
	ret0, _ := ret[0].(*models.AnalyticsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalyticsSummary indicates an expected call of GetAnalyticsSummary.
func (mr *MockAnalyticsRepositoryMockRecorder) GetAnalyticsSummary(ctx, weddingID, period interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalyticsSummary", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetAnalyticsSummary), ctx, weddingID, period)
}

// GetConversions mocks base method.
func (m *MockAnalyticsRepository) GetConversions(ctx context.Context, weddingID primitive.ObjectID, filter *models.AnalyticsFilter) ([]*models.ConversionEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversions", ctx, weddingID, filter)
	ret0, _ := ret[0].([]*models.ConversionEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetConversions indicates an expected call of GetConversions.
func (mr *MockAnalyticsRepositoryMockRecorder) GetConversions(ctx, weddingID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversions", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetConversions), ctx, weddingID, filter)
}

// GetDailyMetrics mocks base method.
func (m *MockAnalyticsRepository) GetDailyMetrics(ctx context.Context, weddingID primitive.ObjectID, startDate, endDate time.Time) ([]models.DailyMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyMetrics", ctx, weddingID, startDate, endDate)
	ret0, _ := ret[0].([]models.DailyMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyMetrics indicates an expected call of GetDailyMetrics.
func (mr *MockAnalyticsRepositoryMockRecorder) GetDailyMetrics(ctx, weddingID, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyMetrics", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetDailyMetrics), ctx, weddingID, startDate, endDate)
}

// GetPageViews mocks base method.
func (m *MockAnalyticsRepository) GetPageViews(ctx context.Context, weddingID primitive.ObjectID, filter *models.AnalyticsFilter) ([]*models.PageView, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageViews", ctx, weddingID, filter)
	ret0, _ := ret[0].([]*models.PageView)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPageViews indicates an expected call of GetPageViews.
func (mr *MockAnalyticsRepositoryMockRecorder) GetPageViews(ctx, weddingID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageViews", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetPageViews), ctx, weddingID, filter)
}

// GetPopularPages mocks base method.
func (m *MockAnalyticsRepository) GetPopularPages(ctx context.Context, weddingID primitive.ObjectID, limit int) ([]models.PageStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularPages", ctx, weddingID, limit)
	ret0, _ := ret[0].([]models.PageStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularPages indicates an expected call of GetPopularPages.
func (mr *MockAnalyticsRepositoryMockRecorder) GetPopularPages(ctx, weddingID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularPages", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetPopularPages), ctx, weddingID, limit)
}

// GetRSVPAnalytics mocks base method.
func (m *MockAnalyticsRepository) GetRSVPAnalytics(ctx context.Context, weddingID primitive.ObjectID, filter *models.AnalyticsFilter) ([]*models.RSVPAnalytics, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRSVPAnalytics", ctx, weddingID, filter)
	ret0, _ := ret[0].([]*models.RSVPAnalytics)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRSVPAnalytics indicates an expected call of GetRSVPAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) GetRSVPAnalytics(ctx, weddingID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRSVPAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetRSVPAnalytics), ctx, weddingID, filter)
}

// GetSystemAnalytics mocks base method.
func (m *MockAnalyticsRepository) GetSystemAnalytics(ctx context.Context) (*models.SystemAnalytics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemAnalytics", ctx)
	ret0, _ := ret[0].(*models.SystemAnalytics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemAnalytics indicates an expected call of GetSystemAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) GetSystemAnalytics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetSystemAnalytics), ctx)
}

// GetTrafficSources mocks base method.
func (m *MockAnalyticsRepository) GetTrafficSources(ctx context.Context, weddingID primitive.ObjectID, limit int) ([]models.TrafficSourceStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrafficSources", ctx, weddingID, limit)
	ret0, _ := ret[0].([]models.TrafficSourceStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrafficSources indicates an expected call of GetTrafficSources.
func (mr *MockAnalyticsRepositoryMockRecorder) GetTrafficSources(ctx, weddingID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrafficSources", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetTrafficSources), ctx, weddingID, limit)
}

// GetWeddingAnalytics mocks base method.
func (m *MockAnalyticsRepository) GetWeddingAnalytics(ctx context.Context, weddingID primitive.ObjectID) (*models.WeddingAnalytics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeddingAnalytics", ctx, weddingID)
	ret0, _ := ret[0].(*models.WeddingAnalytics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeddingAnalytics indicates an expected call of GetWeddingAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) GetWeddingAnalytics(ctx, weddingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeddingAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetWeddingAnalytics), ctx, weddingID)
}

// RefreshSystemAnalytics mocks base method.
func (m *MockAnalyticsRepository) RefreshSystemAnalytics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshSystemAnalytics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshSystemAnalytics indicates an expected call of RefreshSystemAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) RefreshSystemAnalytics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshSystemAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).RefreshSystemAnalytics), ctx)
}

// RefreshWeddingAnalytics mocks base method.
func (m *MockAnalyticsRepository) RefreshWeddingAnalytics(ctx context.Context, weddingID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshWeddingAnalytics", ctx, weddingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshWeddingAnalytics indicates an expected call of RefreshWeddingAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) RefreshWeddingAnalytics(ctx, weddingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshWeddingAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).RefreshWeddingAnalytics), ctx, weddingID)
}

// TrackConversion mocks base method.
func (m *MockAnalyticsRepository) TrackConversion(ctx context.Context, event *models.ConversionEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackConversion", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackConversion indicates an expected call of TrackConversion.
func (mr *MockAnalyticsRepositoryMockRecorder) TrackConversion(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConversion", reflect.TypeOf((*MockAnalyticsRepository)(nil).TrackConversion), ctx, event)
}

// TrackPageView mocks base method.
func (m *MockAnalyticsRepository) TrackPageView(ctx context.Context, pageView *models.PageView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackPageView", ctx, pageView)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackPageView indicates an expected call of TrackPageView.
func (mr *MockAnalyticsRepositoryMockRecorder) TrackPageView(ctx, pageView interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackPageView", reflect.TypeOf((*MockAnalyticsRepository)(nil).TrackPageView), ctx, pageView)
}

// TrackRSVPEvent mocks base method.
func (m *MockAnalyticsRepository) TrackRSVPEvent(ctx context.Context, event *models.RSVPAnalytics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackRSVPEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackRSVPEvent indicates an expected call of TrackRSVPEvent.
func (mr *MockAnalyticsRepositoryMockRecorder) TrackRSVPEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackRSVPEvent", reflect.TypeOf((*MockAnalyticsRepository)(nil).TrackRSVPEvent), ctx, event)
}

// UpdateSystemAnalytics mocks base method.
func (m *MockAnalyticsRepository) UpdateSystemAnalytics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSystemAnalytics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSystemAnalytics indicates an expected call of UpdateSystemAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) UpdateSystemAnalytics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSystemAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).UpdateSystemAnalytics), ctx)
}

// UpdateWeddingAnalytics mocks base method.
func (m *MockAnalyticsRepository) UpdateWeddingAnalytics(ctx context.Context, weddingID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWeddingAnalytics", ctx, weddingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWeddingAnalytics indicates an expected call of UpdateWeddingAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) UpdateWeddingAnalytics(ctx, weddingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWeddingAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).UpdateWeddingAnalytics), ctx, weddingID)
}
