apiVersion: v1
kind: Secret
metadata:
  name: wedding-secrets
  labels:
    app: wedding-invitation-backend
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded values
  mongodb-uri: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNw==  # mongodb://localhost:27017
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # your-super-secret-jwt-key-change-in-production
  jwt-refresh-secret: eW91ci1zdXBlci1zZWNyZXQtcmVmcmVzaC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=  # your-super-secret-refresh-key-change-in-production
  s3-bucket-name: eW91ci13ZWRkaW5nLWFwcC1idWNrZXQ=  # your-wedding-app-bucket
  aws-access-key-id: eW91ci1hd3MtYWNjZXNzLWtleQ==  # your-aws-access-key
  aws-secret-access-key: eW91ci1hd3Mtc2VjcmV0LWtleQ==  # your-aws-secret-key
  sendgrid-api-key: eW91ci1zZW5kZ3JpZC1hcGkta2V5  # your-sendgrid-api-key
---
# Instructions for creating secrets:
# 
# To encode your own values, use:
# echo -n "your-value" | base64
#
# Example for MongoDB URI:
# echo -n "mongodb://username:password@mongodb-service:27017/wedding_invitations" | base64
#
# Example for JWT secrets (generate strong random strings):
# openssl rand -base64 32 | base64
#
# Replace the encoded values above with your actual production values
# before deploying to Kubernetes cluster