// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/analytics.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"
	time "time"
	models "wedding-invitation-backend/internal/domain/models"

	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockAnalyticsService is a mock of AnalyticsService interface.
type MockAnalyticsService struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsServiceMockRecorder
}

// MockAnalyticsServiceMockRecorder is the mock recorder for MockAnalyticsService.
type MockAnalyticsServiceMockRecorder struct {
	mock *MockAnalyticsService
}

// NewMockAnalyticsService creates a new mock instance.
func NewMockAnalyticsService(ctrl *gomock.Controller) *MockAnalyticsService {
	mock := &MockAnalyticsService{ctrl: ctrl}
	mock.recorder = &MockAnalyticsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsService) EXPECT() *MockAnalyticsServiceMockRecorder {
	return m.recorder
}

// CleanupOldAnalytics mocks base method.
func (m *MockAnalyticsService) CleanupOldAnalytics(ctx context.Context, olderThan time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupOldAnalytics", ctx, olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupOldAnalytics indicates an expected call of CleanupOldAnalytics.
func (mr *MockAnalyticsServiceMockRecorder) CleanupOldAnalytics(ctx, olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupOldAnalytics", reflect.TypeOf((*MockAnalyticsService)(nil).CleanupOldAnalytics), ctx, olderThan)
}

// GetAnalyticsSummary mocks base method.
func (m *MockAnalyticsService) GetAnalyticsSummary(ctx context.Context, weddingID primitive.ObjectID, period string) (*models.AnalyticsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalyticsSummary", ctx, weddingID, period)
	ret0, _ := ret[0].(*models.AnalyticsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalyticsSummary indicates an expected call of GetAnalyticsSummary.
func (mr *MockAnalyticsServiceMockRecorder) GetAnalyticsSummary(ctx, weddingID, period interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalyticsSummary", reflect.TypeOf((*MockAnalyticsService)(nil).GetAnalyticsSummary), ctx, weddingID, period)
}

// GetConversions mocks base method.
func (m *MockAnalyticsService) GetConversions(ctx context.Context, weddingID primitive.ObjectID, filter *models.AnalyticsFilter) ([]*models.ConversionEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversions", ctx, weddingID, filter)
	ret0, _ := ret[0].([]*models.ConversionEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetConversions indicates an expected call of GetConversions.
func (mr *MockAnalyticsServiceMockRecorder) GetConversions(ctx, weddingID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversions", reflect.TypeOf((*MockAnalyticsService)(nil).GetConversions), ctx, weddingID, filter)
}

// GetDailyMetrics mocks base method.
func (m *MockAnalyticsService) GetDailyMetrics(ctx context.Context, weddingID primitive.ObjectID, startDate, endDate time.Time) ([]models.DailyMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyMetrics", ctx, weddingID, startDate, endDate)
	ret0, _ := ret[0].([]models.DailyMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyMetrics indicates an expected call of GetDailyMetrics.
func (mr *MockAnalyticsServiceMockRecorder) GetDailyMetrics(ctx, weddingID, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyMetrics", reflect.TypeOf((*MockAnalyticsService)(nil).GetDailyMetrics), ctx, weddingID, startDate, endDate)
}

// GetPageViews mocks base method.
func (m *MockAnalyticsService) GetPageViews(ctx context.Context, weddingID primitive.ObjectID, filter *models.AnalyticsFilter) ([]*models.PageView, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageViews", ctx, weddingID, filter)
	ret0, _ := ret[0].([]*models.PageView)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPageViews indicates an expected call of GetPageViews.
func (mr *MockAnalyticsServiceMockRecorder) GetPageViews(ctx, weddingID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageViews", reflect.TypeOf((*MockAnalyticsService)(nil).GetPageViews), ctx, weddingID, filter)
}

// GetPopularPages mocks base method.
func (m *MockAnalyticsService) GetPopularPages(ctx context.Context, weddingID primitive.ObjectID, limit int) ([]models.PageStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularPages", ctx, weddingID, limit)
	ret0, _ := ret[0].([]models.PageStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularPages indicates an expected call of GetPopularPages.
func (mr *MockAnalyticsServiceMockRecorder) GetPopularPages(ctx, weddingID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularPages", reflect.TypeOf((*MockAnalyticsService)(nil).GetPopularPages), ctx, weddingID, limit)
}

// GetRSVPAnalytics mocks base method.
func (m *MockAnalyticsService) GetRSVPAnalytics(ctx context.Context, weddingID primitive.ObjectID, filter *models.AnalyticsFilter) ([]*models.RSVPAnalytics, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRSVPAnalytics", ctx, weddingID, filter)
	ret0, _ := ret[0].([]*models.RSVPAnalytics)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRSVPAnalytics indicates an expected call of GetRSVPAnalytics.
func (mr *MockAnalyticsServiceMockRecorder) GetRSVPAnalytics(ctx, weddingID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRSVPAnalytics", reflect.TypeOf((*MockAnalyticsService)(nil).GetRSVPAnalytics), ctx, weddingID, filter)
}

// GetSystemAnalytics mocks base method.
func (m *MockAnalyticsService) GetSystemAnalytics(ctx context.Context) (*models.SystemAnalytics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemAnalytics", ctx)
	ret0, _ := ret[0].(*models.SystemAnalytics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemAnalytics indicates an expected call of GetSystemAnalytics.
func (mr *MockAnalyticsServiceMockRecorder) GetSystemAnalytics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemAnalytics", reflect.TypeOf((*MockAnalyticsService)(nil).GetSystemAnalytics), ctx)
}

// GetTrafficSources mocks base method.
func (m *MockAnalyticsService) GetTrafficSources(ctx context.Context, weddingID primitive.ObjectID, limit int) ([]models.TrafficSourceStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrafficSources", ctx, weddingID, limit)
	ret0, _ := ret[0].([]models.TrafficSourceStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrafficSources indicates an expected call of GetTrafficSources.
func (mr *MockAnalyticsServiceMockRecorder) GetTrafficSources(ctx, weddingID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrafficSources", reflect.TypeOf((*MockAnalyticsService)(nil).GetTrafficSources), ctx, weddingID, limit)
}

// GetWeddingAnalytics mocks base method.
func (m *MockAnalyticsService) GetWeddingAnalytics(ctx context.Context, weddingID primitive.ObjectID) (*models.WeddingAnalytics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeddingAnalytics", ctx, weddingID)
	ret0, _ := ret[0].(*models.WeddingAnalytics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeddingAnalytics indicates an expected call of GetWeddingAnalytics.
func (mr *MockAnalyticsServiceMockRecorder) GetWeddingAnalytics(ctx, weddingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeddingAnalytics", reflect.TypeOf((*MockAnalyticsService)(nil).GetWeddingAnalytics), ctx, weddingID)
}

// IsValidEvent mocks base method.
func (m *MockAnalyticsService) IsValidEvent(event string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidEvent", event)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValidEvent indicates an expected call of IsValidEvent.
func (mr *MockAnalyticsServiceMockRecorder) IsValidEvent(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidEvent", reflect.TypeOf((*MockAnalyticsService)(nil).IsValidEvent), event)
}

// IsValidPage mocks base method.
func (m *MockAnalyticsService) IsValidPage(page string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidPage", page)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValidPage indicates an expected call of IsValidPage.
func (mr *MockAnalyticsServiceMockRecorder) IsValidPage(page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidPage", reflect.TypeOf((*MockAnalyticsService)(nil).IsValidPage), page)
}

// RefreshSystemAnalytics mocks base method.
func (m *MockAnalyticsService) RefreshSystemAnalytics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshSystemAnalytics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshSystemAnalytics indicates an expected call of RefreshSystemAnalytics.
func (mr *MockAnalyticsServiceMockRecorder) RefreshSystemAnalytics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshSystemAnalytics", reflect.TypeOf((*MockAnalyticsService)(nil).RefreshSystemAnalytics), ctx)
}

// RefreshWeddingAnalytics mocks base method.
func (m *MockAnalyticsService) RefreshWeddingAnalytics(ctx context.Context, weddingID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshWeddingAnalytics", ctx, weddingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshWeddingAnalytics indicates an expected call of RefreshWeddingAnalytics.
func (mr *MockAnalyticsServiceMockRecorder) RefreshWeddingAnalytics(ctx, weddingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshWeddingAnalytics", reflect.TypeOf((*MockAnalyticsService)(nil).RefreshWeddingAnalytics), ctx, weddingID)
}

// SanitizeCustomData mocks base method.
func (m *MockAnalyticsService) SanitizeCustomData(data map[string]interface{}) map[string]interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SanitizeCustomData", data)
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// SanitizeCustomData indicates an expected call of SanitizeCustomData.
func (mr *MockAnalyticsServiceMockRecorder) SanitizeCustomData(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeCustomData", reflect.TypeOf((*MockAnalyticsService)(nil).SanitizeCustomData), data)
}

// TrackConversion mocks base method.
func (m *MockAnalyticsService) TrackConversion(ctx context.Context, weddingID primitive.ObjectID, sessionID, event string, value float64, properties map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackConversion", ctx, weddingID, sessionID, event, value, properties)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackConversion indicates an expected call of TrackConversion.
func (mr *MockAnalyticsServiceMockRecorder) TrackConversion(ctx, weddingID, sessionID, event, value, properties interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConversion", reflect.TypeOf((*MockAnalyticsService)(nil).TrackConversion), ctx, weddingID, sessionID, event, value, properties)
}

// TrackPageView mocks base method.
func (m *MockAnalyticsService) TrackPageView(ctx context.Context, weddingID primitive.ObjectID, sessionID, page string, req *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackPageView", ctx, weddingID, sessionID, page, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackPageView indicates an expected call of TrackPageView.
func (mr *MockAnalyticsServiceMockRecorder) TrackPageView(ctx, weddingID, sessionID, page, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackPageView", reflect.TypeOf((*MockAnalyticsService)(nil).TrackPageView), ctx, weddingID, sessionID, page, req)
}

// TrackRSVPAbandonment mocks base method.
func (m *MockAnalyticsService) TrackRSVPAbandonment(ctx context.Context, weddingID primitive.ObjectID, sessionID, abandonedStep string, formErrors []string, req *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackRSVPAbandonment", ctx, weddingID, sessionID, abandonedStep, formErrors, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackRSVPAbandonment indicates an expected call of TrackRSVPAbandonment.
func (mr *MockAnalyticsServiceMockRecorder) TrackRSVPAbandonment(ctx, weddingID, sessionID, abandonedStep, formErrors, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackRSVPAbandonment", reflect.TypeOf((*MockAnalyticsService)(nil).TrackRSVPAbandonment), ctx, weddingID, sessionID, abandonedStep, formErrors, req)
}

// TrackRSVPSubmission mocks base method.
func (m *MockAnalyticsService) TrackRSVPSubmission(ctx context.Context, weddingID, rsvpID primitive.ObjectID, sessionID, source string, timeToComplete int64, req *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackRSVPSubmission", ctx, weddingID, rsvpID, sessionID, source, timeToComplete, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackRSVPSubmission indicates an expected call of TrackRSVPSubmission.
func (mr *MockAnalyticsServiceMockRecorder) TrackRSVPSubmission(ctx, weddingID, rsvpID, sessionID, source, timeToComplete, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackRSVPSubmission", reflect.TypeOf((*MockAnalyticsService)(nil).TrackRSVPSubmission), ctx, weddingID, rsvpID, sessionID, source, timeToComplete, req)
}

// ValidatePeriod mocks base method.
func (m *MockAnalyticsService) ValidatePeriod(period string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePeriod", period)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidatePeriod indicates an expected call of ValidatePeriod.
func (mr *MockAnalyticsServiceMockRecorder) ValidatePeriod(period interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePeriod", reflect.TypeOf((*MockAnalyticsService)(nil).ValidatePeriod), period)
}
